### ISSUE TITLE
TypeError when trying to install a docset

### ISSUE THREAD

**Issue by vytotas** [whtsky/Dash.py#4]
Tried to run "dash.py install sqlalchemy", but failed:

```
Traceback (most recent call last):
  File "/usr/local/bin/dash.py", line 9, in <module>
    load_entry_point('dash.py==0.2.1', 'console_scripts', 'dash.py')()
  File "/Library/Python/2.7/site-packages/dash_py/cli.py", line 100, in main
    parguments.run()
  File "/Library/Python/2.7/site-packages/parguments/__init__.py", line 176, in run
    result = cmd(**args)
  File "/Library/Python/2.7/site-packages/parguments/__init__.py", line 19, in __call__
    self._func(**kwargs)
  File "/Library/Python/2.7/site-packages/dash_py/cli.py", line 40, in install
    return [install(n) for n in name]
  File "/Library/Python/2.7/site-packages/dash_py/cli.py", line 58, in install
    install_package(package)
  File "/Library/Python/2.7/site-packages/dash_py/installer.py", line 91, in install_package
    type = package["type"]
TypeError: string indices must be integers, not str
```

**Comment by whtsky** [comment]
Why not download the official SQLAlchemy docset in Dash..?Sent using CloudMagicOn 周日, 1月 25, 2015 at 6:42 下午,  whtsky/Dash.py reply@reply.github.com wrote:            Tried to run "dash.py install sqlalchemy", but failed:

Traceback (most recent call last):
  File "/usr/local/bin/dash.py", line 9, in <module>
    load_entry_point('dash.py==0.2.1', 'console_scripts', 'dash.py')()
  File "/Library/Python/2.7/site-packages/dash_py/cli.py", line 100, in main
    parguments.run()
  File "/Library/Python/2.7/site-packages/parguments/**init**.py", line 176, in run
    result = cmd(**args)
  File "/Library/Python/2.7/site-packages/parguments/**init**.py", line 19, in **call**
    self._func(**kwargs)
  File "/Library/Python/2.7/site-packages/dash_py/cli.py", line 40, in install
    return [install(n) for n in name]
  File "/Library/Python/2.7/site-packages/dash_py/cli.py", line 58, in install
    install_package(package)
  File "/Library/Python/2.7/site-packages/dash_py/installer.py", line 91, in install_package
    type = package["type"]
TypeError: string indices must be integers, not str

**Comment by glyph** [comment]
I was not able to install any docsets at all; only ever got this traceback.
